// TODO: Insert description here. (generated by dbrazdil)

#include <stdint.h>
#include <gtest/gtest.h>

uint64_t __sfi_memory_base;

int main(int argc, char **argv) {
  /* Provide a dummy SFI memory base so that tests
     which do not translate addresses fail. */
  __sfi_memory_base = 0x1000;

  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
