// TODO: Insert description here. (generated by dbrazdil)

#ifndef TRUSTED_RUNTIME_SANDBOX_H_
#define TRUSTED_RUNTIME_SANDBOX_H_

#include <stdint.h>

#define FALSE 0
#define TRUE  1

/* Type for sandboxed pointers, which are 32-bit. */
typedef uint32_t sb_ptr_t;
typedef uint32_t sb_size_t;

typedef int64_t nacl_irt_off_t;

/* Sandbox metadata */
extern uint64_t __sfi_memory_base;

/* Shared functions */
#ifdef __cplusplus
extern "C" {
#endif

void init_system_io(int argc, const char *argv[]);

#ifdef __cplusplus
}
#endif

#endif  // TRUSTED_RUNTIME_SANDBOX_H_
