// TODO: Insert description here. (generated by dbrazdil)

#ifndef TRUSTED_RUNTIME_SANDBOX_INL_H_
#define TRUSTED_RUNTIME_SANDBOX_INL_H_

#include "minsfi.h"
#include <string.h>

static inline void *from_sandbox_addr(sb_ptr_t addr) {
  return (void *) (__sfi_memory_base + addr);
}

static inline void *from_sandbox_addr_range(sb_ptr_t addr, sb_size_t size) {
  assert(addr + size >= addr);
  return (void *) (__sfi_memory_base + addr);
}

static inline void copy_in(sb_ptr_t dest, const void *src, sb_size_t size) {
  assert(dest + size >= dest);
  memcpy((char *) __sfi_memory_base + dest, src, size);
}

#endif  // TRUSTED_RUNTIME_SANDBOX_INL_H_
