// TODO: Insert description here. (generated by dbrazdil)

#include <assert.h>
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>

#include "minsfi.h"
#include "minsfi-inl.h"

static int opt_do_list = FALSE,
           opt_do_extract = FALSE,
           opt_do_extract_withoutpath = FALSE,
           opt_overwrite = FALSE,
           opt_extractdir = FALSE;
static const char *dirname = NULL,
                  *zipfilename = NULL,
                  *filename_to_extract = NULL;

void init_system_io(int argc, const char *argv[]) {
  int i;

  for (i = 1; i < argc; i++) {
    if ((*argv[i]) == '-') {
      const char *p = argv[i]+1;

      while ((*p) != '\0') {
        char c = *(p++);
        if ((c == 'l') || (c == 'L') || (c == 'v') || (c == 'V'))
          opt_do_list = 1;
        if ((c == 'x') || (c == 'X'))
          opt_do_extract = 1;
        if ((c == 'e') || (c == 'E'))
          opt_do_extract = opt_do_extract_withoutpath = 1;
        if ((c == 'o') || (c == 'O'))
          opt_overwrite = 1;
        if ((c == 'd') || (c == 'D')) {
          opt_extractdir = 1;
          dirname = argv[i+1];
          i++;
        }

        if (((c == 'p') || (c == 'P')) && (i + 1 < argc))
          i++;
      }
    } else {
      if (zipfilename == NULL)
        zipfilename = argv[i];
      else if ((filename_to_extract == NULL) && (!opt_extractdir))
        filename_to_extract = argv[i];
    }
  }
}

int allow_read_access(const char *filename) {
  if (!zipfilename || !filename)
    return FALSE;

  if (!strcmp(filename, zipfilename))
    return TRUE;
  return FALSE;
}

int sandboxed_open(sb_ptr_t sb_filename, int flags, int mode) {
  const char *filename = from_sandbox_addr(sb_filename);
  return open(filename, flags, mode);
}

int sandboxed_chdir(sb_ptr_t sb_filename) {
  return chdir(from_sandbox_addr(sb_filename));
}

int sandboxed_close(int fd) {
  return close(fd);
}

int sandboxed_read(int fd, sb_ptr_t sb_buf, sb_size_t size) {
  void *buf = from_sandbox_addr_range(sb_buf, size);
  return read(fd, buf, size);
}

int sandboxed_write(int fd, sb_ptr_t sb_buf, sb_size_t size) {
  void *buf = from_sandbox_addr_range(sb_buf, size);
  return write(fd, buf, size);
}

nacl_irt_off_t sandboxed_lseek(int fd, nacl_irt_off_t offset, int whence) {
  return lseek(fd, offset, whence);
}

int sandboxed_gettimeofday(sb_ptr_t s_tv, sb_ptr_t s_tz) {
  struct timeval *host_tv = from_sandbox_addr(s_tv);
  struct timezone *host_tz = from_sandbox_addr(s_tz);
  return gettimeofday(host_tv, host_tz);
}
